function [muPost, sdPost] = product1dParam(...
                        muAfterMove, sdAfterMove, muSensor, sdSensor)
    muPost = (muAfterMove * sdSensor^2 + muSensor * sdAfterMove^2) / ...
             (sdAfterMove^2 + sdSensor^2);
    sdPost = (sdSensor^2 * sdAfterMove^2) / ...
             (sdAfterMove^2 + sdSensor^2);
end