function H = jacobH(X, Xs)
xs = Xs(1);
ys = Xs(2);
x  = X(1);
y  = X(2);
H = [ -(y - ys)/((x - xs)^2*((y - ys)^2/(x - xs)^2 + 1)), ...
       1/((x - xs)*((y - ys)^2/(x - xs)^2 + 1)), ...
       0;...
     (x - xs)/((x - xs)^2 + (y - ys)^2)^(1/2),...
     (y - ys)/((x - xs)^2 + (y - ys)^2)^(1/2),...
       0];
end